.TH MATRIXGL "1" "June 10th, 2009" "matrixgl" "Matrixgl - The 3D Matrix Screensaver"

.SH NAME
matrixgl - 3D matrix screensaver
.SH SYNOPSIS
.B matrixgl [\fI-CcFfhiusv\fR]
.SH DESCRIPTION
Matrixgl is a 3D matrix screensaver based on The Matrix Reloaded. It features the green scrolling text (or digital rain), that wraps around 3D representations of different characters from the series.
.TP 5
-C --color=COL
Set color of falling text. COL must be one of green, red, blue.
.TP
-c --credits
Show the credits on startup. This option will have no effect if used with --static.
.TP
-F --fs --fullscreen
Run in fullscreen, when run from a terminal. This is the default in xscreensaver.
.TP
-f --fps=SEC
Print FPS stats to the terminal every SEC seconds. SEC is clamped to the range 1,20.
.TP
-h --help
Display this help and exit.
.TP
-i --install
Install matrixgl to xscreensaver, which also installs this man page, as well as adding a copy of the screensaver to /usr/bin, so that it can be run from a terminal. The install will fail if it is not run in the source directory.
.TP
-u --remove
Uninstall matrixgl, removing all added xscreensaver files, this man page, and the copy of the screensaver from /usr/bin. May be run from a terminal.
.TP
-s --static
Enable static mode, which disables the 3D images, making it look like the scrolling text from the original Matrix film.
.TP
-v --version
Output version information and exit.
.TP
--allow-root
Allow matrixgl to be run by the root user, if you really want it to. Disabled by default as a safeguard.
.P
Note: Long options may be passed with a single dash.

.SH KEYS
The following keys can be used while in the screensaver.
.TP 5
c
View Credits
.TP
s
Toggle Static Mode (3D)
.TP
n
Show next image
.TP
p
Pause screensaver
.TP
q
Quit screensaver
.P
Note: Under xscreensaver, matrixgl will be killed before it receives input. These keys only apply when you run matrixgl from a terminal, or when using a different screensaver manager (like KDE or GNOME's).

.SH AUTHOR
Written by  Alexander Zolotov  <nightradio@gmail.com> 2003
.br
Modified by Vincent Launchbury <vincent@doublecreations.com> 2008,2009

.SH REPORTING BUGS
Report matrixgl bugs to <vincent@doublecreations.com>
.br
Matrixgl homepage: <http://www.sourceforge.net/projects/matrixgl/>
.br
Bugs may be reported using the sourceforge tracker system.

.SH COPYRIGHT
Copyright (C) Alexander Zolotov 2003.
.br
Modifications Copyright (C) Vincent Launchbury 2008,2009.
.P
License: GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
Check out the project page at <http://www.sf.net/projects/matrixgl/>.
