.TH matrixgl 1 "June 3rd, 2009"

.SH NAME
matrixgl - 3D matrix screensaver
.SH SYNOPSIS
.B matrixgl [-Cchiusv]
.SH DESCRIPTION
matrixgl is a 3D matrix screensaver based on The Matrix Reloaded. It features the green scrolling text, that wraps around 3D representations of different characters from the series.

.TP 5
-C --color=COL
Set color of falling text. COL must be one of green, red, blue.
.TP
-c --credits
Show the credits on startup. This option will do nothing if used with --static.
.TP
-h --help
Display this help and exit
.TP
-i --install
Install matrixgl to xscreensaver
.TP
-u --remove
Uninstall matrixgl from xscreensaver
.TP
-s --static
Enable static mode (no 3D images)
.TP
-v --version
Output version information and exit

.P
Note: Long options may be passed with a single dash.

.SH KEYS
The following keys can be used while in the screensaver
.TP 5
c
View Credits
.TP
s
Toggle Static Mode (3D)
.TP
n
Show next image
.TP
p
Pause screensaver
.TP
q
Quit screensaver

.SH AUTHOR
Written by Alex Zolotoz <No active email known> 2003
.br
Modified by Vincent Launchbury <vincent@doublecreations.com> 2008,2009

.SH REPORTING BUGS
Report matrixgl bugs to <vincent@doublecreations.com>
.br
matrixgl homepage: <http://www.sourceforge.net/projects/matrixgl/>
.br
Bugs may be reported using the sourceforge tracker system.

.SH COPYRIGHT
Copyright (C) Alex Zolotoz 2003.
.br
Modifications Copyright (C) Vincent Launchbury 2008,2009.
.P
License: GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
Check out the project page at <http://www.sourceforge.net/projects/matrixgl/>.
