.TH MATRIXGL "1" "July 8th, 2009" "matrixgl 2.2.3" "Matrixgl - The 3D Matrix Screensaver"

.SH NAME
matrixgl - 3D matrix screensaver
.SH SYNOPSIS
.B matrixgl [\fI-CcFfhlsv\fR]
.SH DESCRIPTION
Matrixgl is a 3D matrix screensaver based on The Matrix Reloaded. It features the green scrolling text (or digital rain), that wraps around 3D representations of different characters from the series.
.P
Mandatory arguments to long options are mandatory for short options too.
.TP 5
-C --color=COL
Set color of the falling text. COL must be one of green, red, blue.
.TP
-c --credits
Show the credits on startup. This option will have no effect if used with --static.
.TP
-F --fs --fullscreen
Run in fullscreen, when run from a terminal. This is the default in xscreensaver.
.TP
-f --fps[=SEC]
Print FPS stats to the terminal every SEC seconds. SEC is clamped to the range 1,20 and defaults to 2 if not given. Note that the first few stats may be inaccurate due to startup delays.
.TP
-h --help
Display a help message and exit.
.TP
-l --limit=LIM
Limit the framerate to LIM fps. Defaults to 32 fps if this option isn't used. LIM is clamped to the range 1,200. Note: Doesn't work well with very small limits (i.e < 10 fps).
.TP
-s --static
Enable static mode, which disables the 3D images, making it look like the plain scrolling text from the original Matrix film.
.TP
-v --version
Output version and author information and exit.
.TP
--allow-root
Allow matrixgl to be run by the root user, if you really want it to. Disabled by default as a safeguard.
.P
Note: Long options may be passed with a single dash.

.SH KEYS
The following keys can be used while in the screensaver.
.TP 5
c
View Credits
.TP
s
Toggle Static Mode (3D)
.TP
n
Show next image
.TP
p
Pause screensaver
.TP
q
Quit screensaver
.P
Note: Under xscreensaver, matrixgl will be killed before it receives input. These keys only apply when you run matrixgl from a terminal, or when using a different screensaver manager (like KDE or GNOME's).

.SH AUTHOR
Written by  Alexander Zolotov  <nightradio@gmail.com> 2003
      and   Eugene Zolotov     <sentinel@knoppix.ru> 2003.
.br
Modified by Vincent Launchbury <vincent@doublecreations.com> 2008,2009

.SH REPORTING BUGS
Report matrixgl bugs to <vincent@doublecreations.com>
.br
Matrixgl homepage: <http://www.sourceforge.net/projects/matrixgl/>
.br
Bugs may also be reported using the sourceforge tracker system.
.P
To best assist us, please run the following script in the source directory and follow the instructions, before submitting your bug report.
.br
$./gen-bug-report.sh 
.P
More detailed and up-to-date instructions can be found online at <http://www.doublecreations.com/projects/matrixgl/bugs.php>.

.SH COPYRIGHT
Copyright (C) Alexander Zolotov, Eugene Zolotov 2003. 
.br
Modifications Copyright (C) Vincent Launchbury 2008,2009.
.P
License: GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.


.SH SEE ALSO
Project summary:  <http://www.sf.net/projects/matrixgl/>.
.br
Project Website:  <http://www.doublecreations.com/projects/matrixgl/>.
.br
Original Project: <http://knoppix.ru/matrixgl.shtml#english>.

