.TH MATRIXGL "1" "October 13th, 2010" "matrixgl 2.3.1" "Matrixgl - The 3D Matrix Screensaver"

.SH NAME
matrixgl - 3D matrix screensaver
.SH SYNOPSIS
.B matrixgl [\fI\-CcFfhlsv\fR]
.SH DESCRIPTION
Matrixgl is a 3D matrix screensaver based on The Matrix Reloaded. It features
the green scrolling text (or digital rain), that wraps around 3D
representations of different characters from the series.
.P
Mandatory arguments to long options are mandatory for short options too.
.TP 5
\-C \-\-color=COL
Set color of the falling text. COL must be `green', `red' or `blue'.
.TP
\-c \-\-credits
Show the credits on startup. This option will have no effect if used with \-\-static.
.TP
\-F \-\-fs \-\-fullscreen
Run in fullscreen, when run from a terminal. Do not use with xscreensaver (see
\-root)
.TP
\-f \-\-fps[=SEC]
Print FPS stats to the terminal every SEC seconds. SEC is clamped to the range
[1,20] and defaults to 2 if not given. Note that the first few stats may be
inaccurate due to startup delays.
.TP
\-h \-\-help
Display a help message and exit.
.TP
\-l \-\-limit=LIM
Limit the framerate to LIM fps, or as close to it as possible. The default is
32fps, and LIM is clamped to the range [1,200]. \fINote\fR: This feature is
currently poorly implemented, and may either take a long time to slow the frame
rate, or not slow it enough.
.TP
\-s \-\-static
Enable static mode, which disables the display of 3D images. This mimics the
style of the scrolling text from the original film.
.TP
\-v \-\-version
Output version and author information and exit.
.TP
\-\-allow\-root
Allow matrixgl to be run by the root user, if you really want to do so. Disabled
by default as a safeguard.
.TP
\-\-root
Attach to the root window for xscreensaver. This option is set by default
(see xscreensaver\-demo > Matrixgl > Settings > Advanced.)
.P
Note: Long options may be passed with a single dash.

.SH KEYS
The following keys can be used while in the screensaver**
.TP 5
c
View \fIc\fRredits
.TP
s
Toggle \fIs\fRtatic mode (3D)
.TP
n
Show \fIn\fRext image
.TP
p
\fIP\fRause screensaver
.TP
q
\fIQ\fRuit screensaver
.P
**Note: Under xscreensaver, matrixgl will be killed before it receives input.
Therefore, these keys only apply when you run matrixgl from a terminal, or when
using a different screensaver manager (like the ones shipped with KDE or GNOME.)

.SH AUTHORS
Written by  Alexander Zolotov  <nightradio@gmail.com> 2003
      and   Eugene Zolotov     <sentinel@knoppix.ru> 2003
.br
Modified by Vincent Launchbury <vincent@doublecreations.com> 2008\-2010

.SH REPORTING BUGS
Report matrixgl bugs to <vincent@doublecreations.com>
.br
Bugs may also be reported using the sourceforge tracker system.
.P
We have a script that generates a bug report for you. See README for details.

.SH COPYRIGHT
Copyright (C) Alexander Zolotov, Eugene Zolotov 2003. 
.br
Modifications Copyright (C) Vincent Launchbury 2008,2009,2010.
.P
License: GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.


.SH SEE ALSO
Project summary:  <http://www.sf.net/projects/matrixgl/>.
.br
Project Website:  <http://www.doublecreations.com/projects/matrixgl/>.
.br
Original Project: <http://knoppix.ru/matrixgl.shtml#english>.

